### ISSUE TITLE
modals / popups

### ISSUE THREAD

**Issue by jenbrannstrom** [TapTapMobile/narcononuk#14]
Please can you have the texts of these links appear in a modal/popup: http://prntscr.com/8tgzr7

The person must never be sent off-page, all data should appear here, on the current page.

**Comment by jenbrannstrom** [comment]
Can this be loaded on-click only? To reduce page-load times

**Comment by c3j333** [comment]
Which part? The links below it?

**Comment by c3j333** [comment]
Or you mean the location to stay on the current page after the form is submitted? It can be done also thankyou popup will appear instead.

**Comment by jenbrannstrom** [comment]
I mean: if someone clicks any of those links at the bottom (terms, privacy, ...), the popup will then be loaded. As opposed to being inline on index.html, weighing the page down.
Or does it have to be inline if we want a popup?

**Comment by c3j333** [comment]
I see. We can load just the text to the popup. I will have to put those links back at the page footer.

**Comment by jenbrannstrom** [comment]
great

**Comment by c3j333** [comment]
I'm currently working on putting conversion tracking for phone calls. Might have to do it on later part.

**Comment by jenbrannstrom** [comment]
There's been a misunderstanding:

I didn't mean to place the links INSIDE the modal

I mean: 
1. return the privacy links back to the footer
2. on-click they don't open a new page. Instead they open a popup of that page

**Comment by c3j333** [comment]
That privacy links placed inside the modal was the misinterpretation of instruction you posted 2 days ago LOL.  In case you haven't noticed I already did it prior to any changes made this day. I think I understood what you mean and  the work is on progress for modal now.

**Comment by c3j333** [comment]
Changes are on local host and will update online maybe later when I can finish the whole task related to it.

**Comment by jenbrannstrom** [comment]
ah, understood :)
ᐧ

On 22 October 2015 at 16:49, c3j333 notifications@github.com wrote:

> Changes are on local host and will update online maybe later when I can
> finish the whole task related to it.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/TapTapMobile/narcononuk/issues/14#issuecomment-150228605
> .

## 

​
Jen-Lars Brannstrom

​ http://il.linkedin.com/in/jenbrannstrom/
https://twitter.com/jenbrannstrom
skype: auditoryen​

More Qualified Leads http://morequalifiedleads.co.uk/

**Comment by jenbrannstrom** [comment]
brilliant
