### ISSUE TITLE
nav & links

### ISSUE THREAD

**Issue by jenbrannstrom** [TapTapMobile/narcononuk#6]
Please can you add a discreet nav box, similar to this: http://prntscr.com/8t3fta
(example here: http://lp.drug-education.co.uk/rehab.html)

Hard-link it to ALL the pages on http://www.narcononuk.org.uk/

**Comment by jenbrannstrom** [comment]
Very nice nav!
Please can you turn the text  color white?
http://prntscr.com/8tgxho

**Comment by c3j333** [comment]
Done.
