### ISSUE TITLE
add logo's to top

### ISSUE THREAD

**Issue by jenbrannstrom** [TapTapMobile/narcononuk#7]
Please place the logo's that appear in the form, in one of these positions marked: http://prntscr.com/8t3mq1

**Comment by jenbrannstrom** [comment]
Can you swap the logos? The http://prntscr.com/8tgrx3
"Care Quality" logo is much more relevant in the UK - sorry I didn't tell you sooner

**Comment by jenbrannstrom** [comment]
Please edit the mobile view, so the logo and video is on -screen

**Comment by c3j333** [comment]
I just made the modification. Check if it's displaying properly on phone.
