### ISSUE TITLE
call tracking

### ISSUE THREAD

**Issue by jenbrannstrom** [TapTapMobile/narcononuk#8]
Please add call tracking from AdWords:
https://support.google.com/adwords/answer/6095883?hl=en-GB&authuser=0#gfn
[Instructions – local call.txt](https://github.com/TapTapMobile/narcononuk/files/16323/Instructions.local.call.txt)

**Comment by c3j333** [comment]
Done.

**Comment by jenbrannstrom** [comment]
Great!
Once the page goes live we will see if it works - it can be quite tricky stuff to configure :)
